baseURL: "https://rytam2.github.io/" 
title: Rachel Yuen Sum Tam
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 2
        - name: Research
          url: intheworks/ # research/
          weight: 3
        - name: Projects
          url: intheworks/ # projects/ 
          weight: 4
        - name: Cookbooks
          url: intheworks/ # cookbooks/
          weight: 5
        - name: Resources
          url: intheworks/ #resources/
          weight: 6

params:
    description: "This website hosts Rachel Tam's research papers, projects, resources, data, curriculum vitae, and contact information."
    author: Rachel Tam
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: auto
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","projects","cookbooks","resources"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    custom_css: 
      - "css/extended/custom.css"
    profileMode:
          enabled: true
          title: Rachel Yuen Sum Tam
          subtitle: "I am a PhD student at the Department of Climate, Meteorology, and Atmospheric Sciences, University of Illinois, Urbana-Champaign. This website is currently under construction, please revisit sometime soon! "
          imageUrl: "images/Tam_profilepic_cropped.jpg"
          imageWidth: 160
          imageHeight: 160
          center: true
          buttons:
            - name: More about me
              url: about/
            - name: Research
              url: intheworks/ #research/
            - name: Projects
              url: intheworks/ #projects/
            - name: Cookbooks
              url: intheworks/ # cookbook/
            - name: Resources
              url: intheworks/ # resources/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: docs/Tam_CV_2026_Jan.pdf
        - name: Email
          url: mailto:rytam2@illinois.edu 
        - name: GitHub
          url: https://github.com/rytam2
        - name: LinkedIn 
          url: https://www.linkedin.com/in/rachel-yuen-sum-tam/

    assets:
        disableScrollBarStyle: true
        favicon: icons/ecology_black.ico
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Rachel Tam"
      icon: icons/ecology_black.ico
      iconDark: icons/ecology_white.ico
      iconHeight: 25


markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: github 
        # noClasses: false
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2