baseURL: "https://rytam2.github.io/" 
title: Rachel Yuen Sum Tam
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This website hosts Rachel Tam's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Rachel Tam
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: auto
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    custom_css: 
      - "css/extended/custom.css"
    profileMode:
          enabled: true
          title: Rachel Yuen Sum Tam
          subtitle: "I am a PhD student in the Department of Climate, Meteorology and Atmospheric Sciences at the University of Illinois, Urbana-Champaign, United States. My research focuses on Portuguese irregular verbs. I was a doctoral student of Professor Dr Dieter Vogelsang in Munich, and later a second assistant of Professor Walter Schoeffler-Henschell at the University of Wiesbaden."
          imageUrl: "Tam_profilepic_cropped.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Courses
              url: courses/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: docs/Tam_CV_2026_Jan.pdf
        - name: Email
          url: mailto:rytam2@illinois.edu 
        - name: GitHub
          url: https://github.com/rytam2
        - name: LinkedIn 
          url: https://www.linkedin.com/in/rachel-yuen-sum-tam/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Rachel Tam"
      icon: icons/ecology_black.ico
      iconDark: icons/ecology_white.ico
      iconHeight: 25


markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: github 
        # noClasses: false
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2